Repository apache/maven-jxr, pull requests merged in 2024-12, with the labels that each got.

#129 Remove plexus components.xml
  maven-jxr-plugin/src/main/resources/META-INF/plexus/components.xml
Labels: maintenance

#128 Cleanup and verify dependencies
  maven-jxr-plugin/pom.xml
  maven-jxr/pom.xml
Labels: dependencies, maintenance

#130 [JXR-195] Convert tests to JUnit 5
  maven-jxr-plugin/pom.xml
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/AbstractJxrTestCase.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/JxrReportTest.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/JxrTestReportTest.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/AggregateTestMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/DefaultConfigurationMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/ExcludeConfigurationMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/IncludeConfigurationMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/NoJavadocDirMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/NoJavadocLinkConfigurationMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/PomMavenProjectStub.java
  maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/TestSourceDirMavenProjectStub.java
  maven-jxr/pom.xml
  maven-jxr/src/test/java/org/apache/maven/jxr/DirectoryIndexerTest.java
  maven-jxr/src/test/java/org/apache/maven/jxr/IncludeExcludeTest.java
  maven-jxr/src/test/java/org/apache/maven/jxr/JXR141Test.java
  maven-jxr/src/test/java/org/apache/maven/jxr/JavaCodeTransformTest.java
  maven-jxr/src/test/java/org/apache/maven/jxr/JxrBeanTest.java
  maven-jxr/src/test/java/org/apache/maven/jxr/pacman/JavaFileImplTest.java
  maven-jxr/src/test/java/org/apache/maven/jxr/util/SimpleWordTokenizerTest.java
  pom.xml
Labels: dependencies
